TiminsHospitalProjectV3/Models/NewsItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TiminsHospitalProjectV3.Models
{//Table name
    public class NewsItem
    {
//Primary key of table
        [Key]
        public int NewsItemID { get; set; }

        public string Title { get; set; }

        public string NewsBody { get; set; }
        public DateTime NewItemDate { get; set; }
//The following two fields allow for detection of a picture and that type of picture(IE JPG)
        public bool NewsItemHasPic { get; set; }

        public string NewsItemPicExtension { get; set; }

//The ForegnKey is of the loged in user ID 
        //[ForeignKey("AccountViewModels")]
        [ForeignKey("User")]
        public string UserID { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
 //The DTO helps keep data safe by adding a degree of seperation to the database
    public class NewsItemDto
    {
        public int NewsItemID { get; set; }

        public string Title { get; set; }

        public string NewsBody { get; set; }
        public DateTime NewItemDate { get; set; }
        public bool NewsItemHasPic { get; set; }

        public string NewsItemPicExtension { get; set; }


        public string UserID { get; set; }
    }
}

TiminsHospitalProjectV3/Controllers/NewsItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using TiminsHospitalProjectV3.Models;
using TiminsHospitalProjectV3.Models.ViewModels;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Diagnostics;
using System.Web.Script.Serialization;
//The following Using statement allows for access of logged in users credentials
using Microsoft.AspNet.Identity;


namespace TiminsHospitalProjectV3.Controllers
{
    public class NewsItemController : Controller
    {
        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;


        static NewsItemController()
        {
            //The following defines how cookies will be handled
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false,
                //This allows us to use cookies to check admin status of logged in user
                UseCookies = false

            };
            client = new HttpClient(handler);
            //change this to match your own local port number
            client.BaseAddress = new Uri("http://hospitalproject-env.eba-fm6cqgtc.us-east-2.elasticbeanstalk.com/api/");
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));



        }
        //This method actually gets the cookies
        private void GetApplicationCookie()
        {
            string token = "";
           
            client.DefaultRequestHeaders.Remove("Cookie");
            if (!User.Identity.IsAuthenticated) return;

            HttpCookie cookie = System.Web.HttpContext.Current.Request.Cookies.Get(".AspNet.ApplicationCookie");
            if (cookie != null) token = cookie.Value;

            Debug.WriteLine("Token Submitted is : " + token);
            if (token != "") client.DefaultRequestHeaders.Add("Cookie", ".AspNet.ApplicationCookie=" + token);

            return;
        }
        // Allows us to acces the get news items
        public ActionResult List()
        {
            ListNewsItems ViewModel = new ListNewsItems();
            ViewModel.isadmin = User.IsInRole("Admin"); //Checks to see if the user is an admin

            string url = "NewsItemData/GetNewsItems";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                //Produces a lsit of news items through the DTO
                IEnumerable<NewsItemDto> SelectedEvents = response.Content.ReadAsAsync<IEnumerable<NewsItemDto>>().Result;
                ViewModel.newsItems = SelectedEvents;

                return View(ViewModel);

            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        //Gets the specified details of an individual news item
        public ActionResult Details(int id)
        {
            //instantiates the ShowNEwsITem viewmodle
            ShowNewsItem ViewModel = new ShowNewsItem();
            string url = "NewsItemData/FindNewsItem/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
               //Finds the info for one specific news item through the dto
                NewsItemDto SelectedNewsItem = response.Content.ReadAsAsync<NewsItemDto>().Result;
                ViewModel.newsItem = SelectedNewsItem;



                return View(ViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        public ActionResult Create()
        {
            return View();
        }

    
        [HttpPost]
        [ValidateAntiForgeryToken()]
        [Authorize(Roles = "Admin")]

        public ActionResult Create(NewsItem NewsItemInfo)
        {
            //Gets the cookie to check for admin
            GetApplicationCookie();
            string url = "NewsItemData/AddNewsItem";
            NewsItemInfo.UserID = User.Identity.GetUserId();

            Debug.WriteLine(jss.Serialize(NewsItemInfo));
            HttpContent content = new StringContent(jss.Serialize(NewsItemInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                try
                {
                    int newsItemid = response.Content.ReadAsAsync<int>().Result;
                    return RedirectToAction("Details", new
                    {
                        id = newsItemid
                    });

                }
                catch (Exception e)
                {
                    Debug.WriteLine(NewsItemInfo);
                    return RedirectToAction("List");
                }
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        //finds the news item to be deleted
        [HttpGet]
        [Authorize(Roles = "Admin")]

        public ActionResult DeleteConfirm(int id)
        {
            string url = "NewsItemData/FindNewsItem/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            
            if (response.IsSuccessStatusCode)
            {
                //Put data into Hop data transfer object
                NewsItemDto SelectedNewsItem = response.Content.ReadAsAsync<NewsItemDto>().Result;
                return View(SelectedNewsItem);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        //Confirms and actually deletes the specific news item
        [HttpPost]
        [ValidateAntiForgeryToken()]
        [Authorize(Roles = "Admin")]

        public ActionResult Delete(int id)
        {
            //gets the cookie to check for admin
            GetApplicationCookie();
            string url = "NewsItemData/DeleteNewsItem/" + id;
       
            HttpContent content = new StringContent("");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
 

            if (response.IsSuccessStatusCode)
            {

                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }

        }
        [Authorize(Roles = "Admin")]
        //allows the view to find the specific news item to be edited
        public ActionResult Edit(int id)
        {
            UpdateNewsItem ViewModel = new UpdateNewsItem();

            string url = "NewsItemData/FindNewsItem/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                //Put data into newsitem data transfer object
                NewsItemDto SelectedNewsItem = response.Content.ReadAsAsync<NewsItemDto>().Result;
                ViewModel.newsItem = SelectedNewsItem;
             
                return View(ViewModel);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

       //Allows the editing of the specified news item
        [Authorize(Roles = "Admin")]

        [HttpPost]
        [ValidateAntiForgeryToken()]

        public ActionResult Edit(int id, NewsItem NewsItemInfo, HttpPostedFileBase NewsItemImage)
        {
            //gets cookie for security
            GetApplicationCookie();

            string url = "NewsItemData/UpdateNewsItem/" + id;
            NewsItemInfo.UserID = User.Identity.GetUserId();

            Debug.WriteLine(jss.Serialize(NewsItemInfo));
            HttpContent content = new StringContent(jss.Serialize(NewsItemInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            Debug.WriteLine(response.StatusCode);
            if (response.IsSuccessStatusCode)
            {///UPDATE BELLOW
                if (NewsItemImage != null)
                {
                    Debug.WriteLine("Calling Update Image method.");
                    //Send over image data for the specific news item
                    url = "NewsItemData/UpdateNewsItemImage/" + id;

                    MultipartFormDataContent requestcontent = new MultipartFormDataContent();
                    HttpContent imagecontent = new StreamContent(NewsItemImage.InputStream);
                    requestcontent.Add(imagecontent, "NewsItemImage", NewsItemImage.FileName);
                    response = client.PostAsync(url, requestcontent).Result;
                }
                return RedirectToAction("Details", new { id = id });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        /// returns an erro in the event of an error
        public ActionResult Error()
        {
            return View();
        }
    }
}

TiminsHospitalProjectV3/Views/NewsItem/Create.cshtml
@model TiminsHospitalProjectV3.Models.NewsItemDto

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <!--This is using the built in razor validation-->

    <div class="form-horizontal">
        <h4>NewsItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NewsBody, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewsBody, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewsBody, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NewItemDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewItemDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewItemDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--
        <div class="form-group">
            @Html.LabelFor(model => model.NewsItemHasPic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.NewsItemHasPic)
                    @Html.ValidationMessageFor(model => model.NewsItemHasPic, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NewsItemPicExtension, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewsItemPicExtension, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewsItemPicExtension, "", new { @class = "text-danger" })
            </div>
        </div>
        -->
        <!--<div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>-->

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TiminsHospitalProjectV3/Views/NewsItem/DeleteConfirm.cshtml
@model TiminsHospitalProjectV3.Models.NewsItemDto

@{
    ViewBag.Title = "DeleteConfirm";
}

<h2>DeleteConfirm</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NewsItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NewsBody)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NewsBody)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NewItemDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NewItemDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NewsItemHasPic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NewsItemHasPic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NewsItemPicExtension)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NewsItemPicExtension)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>

    </dl>
    <div>
    @using (Html.BeginForm("Delete", "NewsItem", new { id = Model.NewsItemID }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "List")
        </div>
    }
</div>
    }
</div>

TiminsHospitalProjectV3/Views/NewsItem/Details.cshtml
@model TiminsHospitalProjectV3.Models.ViewModels.ShowNewsItem

@{
    ViewBag.Title = "Details";
}

<h2> @Html.DisplayFor(model => model.newsItem.Title)</h2>
@{
    //Use server rendering to determine an image
    string pic = "/Content/NewsItems/default.jpg";
    string alt = "No Profile Picture Provided.";
    if (Model.newsItem.NewsItemHasPic)
    {
        pic = "/Content/NewsItems/" + Model.newsItem.NewsItemID + "." + Model.newsItem.NewsItemPicExtension;
        alt = "Picture Of Event ";
    }
}
<div>
    <img src="@pic" alt="@alt" width="200" />
    <hr />
    <p>
        <b>Publication Date:</b>  @Html.DisplayFor(model => model.newsItem.NewItemDate)
    </p>

    <br />

    <p>
        @Html.DisplayFor(model => model.newsItem.NewsBody)
    </p>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.newsItem.NewsItemID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TiminsHospitalProjectV3/Views/NewsItem/Edit.cshtml
u
@model TiminsHospitalProjectV3.Models.ViewModels.UpdateNewsItem

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<!--WHEN CREATING EDDIT ADD NAMES TO EVERYTHING, INDICATE UPDATE VIEWMODEL AND DONT FORGET NAME FOR "HIDDENFOR"-->
@using (Html.BeginForm("Edit", "NewsItem", new { id = Model.newsItem.NewsItemID }, FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()
    <!--This is using the built in razor validation-->

    <div class="form-horizontal">
        <h4>NewsItem</h4>
        <hr />


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.newsItem.NewsItemID, new { Name = "NewsItemID" })

        <div class="form-group">
            @Html.LabelFor(model => model.newsItem.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.newsItem.Title, new { htmlAttributes = new { @class = "form-control", Name = "Title" } })
                @Html.ValidationMessageFor(model => model.newsItem.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.newsItem.NewsBody, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.newsItem.NewsBody, new { htmlAttributes = new { @class = "form-control", Name = "NewsBody" } })
                @Html.ValidationMessageFor(model => model.newsItem.NewsBody, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.newsItem.NewItemDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.newsItem.NewItemDate, new { htmlAttributes = new { @class = "form-control", Name = "NewItemDate" } })
                @Html.ValidationMessageFor(model => model.newsItem.NewItemDate, "", new { @class = "text-danger" })
            </div>
        </div>


        <!-- <div class="form-group">
             @Html.LabelFor(model => model.newsItem.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
             <div class="col-md-10">
                 @Html.EditorFor(model => model.newsItem.UserID, new { htmlAttributes = new { @class = "form-control", Name = "UserID" } })
                 @Html.ValidationMessageFor(model => model.newsItem.UserID, "", new { @class = "text-danger" })
             </div>
         </div>
            -->



        <!--IMAGE UPLOAD-->

        <div class="col-md-6">
            <div class="form-group">
                <div class="col-md-12">Picture:</div>
                <div class="col-md-12">
                    <input type="file" name="NewsItemImage" />


                </div>

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TiminsHospitalProjectV3/Views/NewsItem/List.cshtml
@model TiminsHospitalProjectV3.Models.ViewModels.ListNewsItems



@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Title
        </th>

        <th>
            Date
        </th>
        @if (Model.isadmin)
        {
            <th>
                News Item Has Picure?
            </th>
            <th>
                Pic Extention
            </th>
            <th>
                Last Created/updated by:
            </th>
        }
        <th>
            Details
        </th>
    </tr>

    @foreach (var item in Model.newsItems)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Title)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.NewItemDate)
    </td>
    @if (Model.isadmin)
    {
        <td>
            @Html.DisplayFor(modelItem => item.NewsItemHasPic)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NewsItemPicExtension)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserID)
        </td>
    }
<td>
    @if (Model.isadmin)
    {
        @Html.ActionLink("Edit", "Edit", new { id = item.NewsItemID }) 
        @Html.ActionLink("Delete", "DeleteConfirm", new { id = item.NewsItemID })
    }
    @Html.ActionLink("Details", "Details", new { id = item.NewsItemID }) 
</td>
    </tr>
    }

</table>