TiminsHospitalProjectV3/Models/Appointment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;


namespace TiminsHospitalProjectV3.Models
{
    public enum AppointmentStatus
    {
       
        Accepted,       
        Rejected,              
        Pending
    }
    public class Appointment
    {



        [Key]
        public int ID { get; set; }

        [DisplayName("Patient")]
        [ForeignKey("PatientUser")]
        public string PatientID { get; set; }
        public virtual ApplicationUser PatientUser { get; set; }

        [DisplayName("Physician")]
        [ForeignKey("PhysicianUser")]
        public string PhysicianID { get; set; }
        public virtual ApplicationUser PhysicianUser { get; set; }

        [Required]
        public string RequestDatetime { get; set; }
        [Required]
        public string Subject { get; set; }
        [Required]
        public string Message { get; set; }
        [Required]
        public AppointmentStatus Status { get; set; }
        [Required]
        public string SentOn { get; set; }
        public string DecisionMadeOn { get; set; }





    }
}

TiminsHospitalProjectV3/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Diagnostics;
using TiminsHospitalProjectV3.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using TiminsHospitalProjectV3.Models.ViewModels;
using System.Globalization;

namespace TiminsHospitalProjectV3.Controllers
{
    public class AppointmentsController : Controller
    {
        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;
        private int perPage = 10;//number of record per page

        /// <summary>
        /// This allows us to access a pre-defined C# HttpClient 'client' variable for sending POST and GET requests to the data access layer.
        /// </summary>
        static AppointmentsController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false,
                //cookies are manually set in RequestHeader
                UseCookies = false
            };

            client = new HttpClient(handler);
            //change this to match your own local port number
            client.BaseAddress = new Uri("http://hospitalproject-env.eba-fm6cqgtc.us-east-2.elasticbeanstalk.com/api/");
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));
        }

        /// <summary>
        /// Grabs the authentication credentials which are sent to the Controller.
        /// This is NOT considered a proper authentication technique for the WebAPI. It piggybacks the existing authentication set up in the template for Individual User Accounts. Considering the existing scope and complexity of the course, it works for now.
        /// 
        /// Here is a descriptive article which walks through the process of setting up authorization/authentication directly.
        /// https://docs.microsoft.com/en-us/aspnet/web-api/overview/security/individual-accounts-in-web-api
        /// </summary>
        private void GetApplicationCookie()
        {
            string token = "";
            //HTTP client is set up to be reused, otherwise it will exhaust server resources.
            //This is a bit dangerous because a previously authenticated cookie could be cached for
            //a follow-up request from someone else. Reset cookies in HTTP client before grabbing a new one.
            client.DefaultRequestHeaders.Remove("Cookie");
            if (!User.Identity.IsAuthenticated) return;

            HttpCookie cookie = System.Web.HttpContext.Current.Request.Cookies.Get(".AspNet.ApplicationCookie");
            if (cookie != null) token = cookie.Value;

            //collect token as it is submitted to the controller
            //use it to pass along to the WebAPI.
            Debug.WriteLine("Token Submitted is : " + token);
            if (token != "") client.DefaultRequestHeaders.Add("Cookie", ".AspNet.ApplicationCookie=" + token);

            return;
        }
        [Authorize(Roles = "Patient,Physician,Admin")]
        // GET: Appointments/List?{pageNum}
        public ActionResult List(int pageNum = 1, string searchStatus = "all")
        {
            string url = "", paginatedUrl = "";
            //grab all appointments
            if (User.IsInRole("Admin"))
            {
                paginatedUrl = "AppointmentsData/GetAppointmentsPage";
                url = "AppointmentsData/GetAppointments";
            }

            else if (User.IsInRole("Patient") || User.IsInRole("Physician"))
            {
                paginatedUrl = "AppointmentsData/FindUserAppointmentsPage";
                url = "AppointmentsData/FindUserAppointments";
                url = url + "/" + User.Identity.GetUserId();
                paginatedUrl += "/" + User.Identity.GetUserId();
            }


            if (url != "")
            {
                url += "?searchStatus=" + searchStatus;

                //sends http request and retrieves the response
                HttpResponseMessage response = client.GetAsync(url).Result;

                //grab the result if the request is a success
                if (response.IsSuccessStatusCode)
                {
                    IEnumerable<Appointment> appointments = response.Content.ReadAsAsync<IEnumerable<Appointment>>().Result;
                    //determines the max number of pages
                    int nberItems = appointments.Count();
                    int maxPageNber = (int)Math.Ceiling((decimal)nberItems / perPage);
                    // Lower boundary for Max Page number
                    if (maxPageNber < 1) maxPageNber = 1;
                    // Lower boundary for Page Number
                    if (pageNum < 1) pageNum = 1;
                    // Upper Bound for Page Number
                    if (pageNum > maxPageNber) pageNum = maxPageNber;
                    // The Record Index of our Page Start
                    int startIndex = perPage * (pageNum - 1);

                    //Helps us generate the HTML which shows "Page 1 of ..." on the list view
                    ViewData["PageNum"] = pageNum;
                    ViewData["MaxPageNum"] = maxPageNber;
                    ViewData["searchStatus"] = searchStatus;

                    //get the list of appoinments according to pagination
                    paginatedUrl += "/" + startIndex + "/" + perPage + "?searchStatus=" + searchStatus; ;
                    response = client.GetAsync(paginatedUrl).Result;
                    appointments = response.Content.ReadAsAsync<IEnumerable<Appointment>>().Result;
                    foreach (Appointment appt in appointments)
                    {
                        appt.PatientUser = new ApplicationDbContext().Users.Find(appt.PatientID);
                        appt.PhysicianUser = new ApplicationDbContext().Users.Find(appt.PhysicianID);
                    }
                    return View(appointments);
                }
                else
                {
                    // If we reach here something went wrong with our list algorithm
                    return RedirectToAction("Error");
                }

            }
            else
            {
                // If we reach here something went wrong with our list algorithm
                return RedirectToAction("Error");
            }


        }

        [Authorize(Roles = "Patient,Physician,Admin")]
        // GET: Appointments/Details/5
        public ActionResult Details(int id)
        {
            string url = "AppointmentsData/GetAppointment/" + id;
            //sends http request and retrieves the response
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                Appointment appt = response.Content.ReadAsAsync<Appointment>().Result;
                appt.PatientUser = new ApplicationDbContext().Users.Find(appt.PatientID);
                appt.PhysicianUser = new ApplicationDbContext().Users.Find(appt.PhysicianID);
                ViewData["listStatus"] = Enum.GetValues(typeof(AppointmentStatus));
                return View(appt);
            }
            else
            {
                // If we reach here something went wrong with our list algorithm
                return RedirectToAction("Error");
            }

        }
        [HttpPost]
        [Authorize(Roles = "Physician")]
        [ValidateAntiForgeryToken()]
        // POST: Appointments/ChangeStatus/5/Accepted
        public ActionResult ChangeStatus(int id, AppointmentStatus status)
        {
            string url = "AppointmentsData/GetAppointment/" + id;
            //sends http request and retrieves the response
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                Appointment appt = response.Content.ReadAsAsync<Appointment>().Result;
                appt.Status = status;
                appt.DecisionMadeOn = DateTime.Now.ToString("yyyy/MM/dd hh:mm tt");
                //pass along authentication credential in http request
                GetApplicationCookie();

                //update the appointment
                url = "AppointmentsData/UpdateAppointment/" + id;

                HttpContent content = new StringContent(jss.Serialize(appt));
                content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                response = client.PostAsync(url, content).Result;
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Details", new { id = id });

                }
                else
                {
                    return RedirectToAction("Error");

                }


            }
            else
            {
                // If we reach here something went wrong with our list algorithm
                return RedirectToAction("Error");
            }

        }



        [Authorize(Roles = "Patient,Physician")]
        // GET: Appointments/Create
        public ActionResult Create()
        {
            IdentityRole role = null;
            //if user's role is 'patient' fetch the users with 'Doctor' role and vice versa
            if (User.IsInRole("Patient"))
            {
                role = new ApplicationDbContext().Roles.SingleOrDefault(m => m.Name == "Physician");

            }

            else
            {
                role = new ApplicationDbContext().Roles.SingleOrDefault(m => m.Name == "Patient");
            }
            CreateViewAppointment viewModel = new CreateViewAppointment();
            viewModel.UsersInRole = new ApplicationDbContext().Users.Where(m => m.Roles.Any(r => r.RoleId == role.Id)).ToList();

TiminsHospitalProjectV3/Views/Appointments/Create.cshtml
@model TiminsHospitalProjectV3.Models.ViewModels.CreateViewAppointment
@Styles.Render("~/Content/Appointments/Create.css")



@{
    ViewBag.Title = "Create";
    var user_id = (String)ViewData["user_id"];
}

<h2>Request An appointment</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    if (User.IsInRole("Patient"))
    {
        <input type="hidden" id="PatientID" value="@user_id" name="PatientID" />



    }

    else
    {
        <input type="hidden" id="PhysicianID" value="@user_id" name="PhysicianID" />

    }

    <div class="form-horizontal">
        <h3>New Request Of Appointment</h3>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @if (User.IsInRole("Physician"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.PatientID, "Patient:", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    <select name="PatientID" id="PatientID" class="form-control">
                        @foreach (var patient in Model.UsersInRole)
                        {
                            <option value="@patient.Id">@patient.FirstName @patient.LastName</option>
                        }

                    </select>
                    @* @Html.DropDownListFor(model => model.Appointment.PatientID, new SelectList(Model.UsersInRole), "Select a physician")
                    *@
                    @Html.ValidationMessage("PatientID", "", new { @class = "text-danger" })
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                @Html.LabelFor(model => model.PhysicianID, "Physician:", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    <select name="PhysicianID" id="PhysicianID" class="form-control">
                        @foreach (var physician in Model.UsersInRole)
                        {
                            <option value="@physician.Id">Dr @physician.FirstName @physician.LastName</option>
                        }

                    </select>
                    @* @Html.DropDownListFor(model => model.Appointment.PatientID, new SelectList(Model.UsersInRole), "Select a physician")
                    *@
                    @Html.ValidationMessage("PhysicianID", "", new { @class = "text-danger" })
                </div>
            </div>

        }


        <div class="form-group">
            @Html.LabelFor(Model => Model.RequestDatetime, "Requested Date and Time:", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.RequestDatetime, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.RequestDatetime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, "Subject:", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, "Message:", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.TextAreaFor(model => model.Message, new { @class = "form-control", @cols = 12, @rows = 5 })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <input type="submit" value="Create" class="btn btn-default" id="btn-create"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/Appointments/create.js")
}

TiminsHospitalProjectV3/Views/Appointments/DeleteConfirm.cshtml
@model TiminsHospitalProjectV3.Models.Appointment
@Styles.Render("~/Content/Appointments/Delete.css")

@{
    ViewBag.Title = "DeleteConfirm";
    DateTime apptDatetime = DateTime.Parse(Model.RequestDatetime, new System.Globalization.CultureInfo("en-CA"));
    string str_apptDatetime = apptDatetime.ToString("F", new System.Globalization.CultureInfo("en-CA"));

}
<div id="delete-wrapper">
<div class="form-actions no-color">

    @Html.ActionLink("Back to List", "List")
</div>
<h2>Confirmation Of Deletion</h2>
<hr />
<h3>
    Are you sure you want to delete the appointment on <strong> @str_apptDatetime </strong> with
    <strong>@ViewData["recipientUsername"]</strong>?
</h3>

@using (Html.BeginForm("Delete", "Appointments", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID, new { Name = "id" })

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" />

    </div>
}
</div>

TiminsHospitalProjectV3/Views/Appointments/Details.cshtml
@model TiminsHospitalProjectV3.Models.Appointment
@Styles.Render("~/Content/Appointments/Details.css")

@{
    ViewBag.Title = "Details";
    Array statuses = (TiminsHospitalProjectV3.Models.AppointmentStatus[])ViewData["listStatus"];
}



<div class="container" id="details-wrapper">
    <h2> Appointment Details</h2>

    <table class="table">

        <tbody>
            <tr>
                <th scope="row">@Html.DisplayName("Patient"):</th>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.PatientUser.FirstName)
                    @Html.DisplayFor(modelItem => modelItem.PatientUser.LastName)
                </td>
            </tr>
            <tr>
                <th scope="row">@Html.DisplayName("PHysician"):</th>
                <td>
                    Dr
                    @Html.DisplayFor(modelItem => modelItem.PhysicianUser.FirstName)
                    @Html.DisplayFor(modelItem => modelItem.PhysicianUser.LastName)
                </td>
            </tr>
            <tr>
                <th scope="row">@Html.DisplayName("Sent On"):</th>
                <td> @Html.DisplayFor(modelItem => Model.SentOn) </td>
            </tr>
            <tr>
                <th scope="row">@Html.DisplayName("Decision Made On"):</th>
                <td> @Html.DisplayFor(modelItem => Model.DecisionMadeOn) </td>
            </tr>
            <tr>
                <th scope="row">@Html.DisplayName("Date and Time Requested"):</th>
                <td> @Html.DisplayFor(modelItem => Model.RequestDatetime) </td>
            </tr>
            <tr>
                <th scope="row">@Html.DisplayNameFor(model => model.Status):</th>
                <td> @Html.DisplayFor(modelItem => Model.Status) </td>
            </tr>
            <tr>
                <th scope="row">@Html.DisplayNameFor(model => model.Subject):</th>
                <td> @Html.DisplayFor(modelItem => Model.Subject) </td>
            </tr>
            <tr>
                <th scope="row">@Html.DisplayNameFor(model => model.Message):</th>
                <td> @Html.DisplayFor(modelItem => Model.Message) </td>
            </tr>

        </tbody>
    </table>
    @if (User.IsInRole("Physician") && string.Equals("Pending", Model.Status.ToString()))
    {
        using (Html.BeginForm("ChangeStatus", "Appointments", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <h3>Update the status</h3>
            @Html.HiddenFor(modelItem => modelItem.ID, new { Name = "id" })
            <div class="form-group" >

                <div class="col-md-5" id="dropdown-status">

                    <select name="status" class="form-control">

                        @foreach (var s in statuses)
                        {
                            if (Model.Status.ToString() == s.ToString())
                            {
                                <option value="@s.ToString()" selected>@s.ToString()</option>
                            }
                            else
                            {
                                <option value="@s.ToString()">@s.ToString()</option>
                            }
                        }
                    </select>

                    @Html.ValidationMessage("Status", "", new { @class = "text-danger" })
                </div>

                <div class="col-md-4">
                    <input type="submit" value="Change the status" class="btn btn-default" id="btn-update"/>
                </div>


            </div>

        }
    }

</div>
<div class="link-wrapper">
     @if (Model.Status == TiminsHospitalProjectV3.Models.AppointmentStatus.Pending) {
		@Html.ActionLink("Edit |", "Edit", new { id = Model.ID }) 
    }
    @Html.ActionLink("Back to List", "List")
</div>

TiminsHospitalProjectV3/Views/Appointments/Edit.cshtml
@model TiminsHospitalProjectV3.Models.ViewModels.UpdateViewAppointment
@Styles.Render("~/Content/Appointments/Edit.css")

@{
    ViewBag.Title = "Edit";
    var physicianName = "Dr " + Model.PhysicianUser.FirstName + " " + Model.PhysicianUser.LastName;
    var patientName = Model.PatientUser.FirstName + " " + Model.PatientUser.LastName;
}

<h2>Edit Appointment</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID, new { Name = "id" })
        @Html.HiddenFor(model => model.SentOn, new { Name = "SentOn" })
        @Html.HiddenFor(model => model.Status, new { Name = "Status" })
        @Html.HiddenFor(model => model.PatientID, new { Name = "PatientID" })
        @Html.HiddenFor(model => model.PhysicianID, new { Name = "PhysicianID" })



        @if (User.IsInRole("Physician"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.PatientID, "Patient:", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    <input type="text" class="form-control" value="@patientName" disabled />

                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                @Html.LabelFor(model => model.PhysicianID, "Physician:", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    <input type="text" class="form-control" value="@physicianName" disabled />


                </div>
            </div>

        }


        <div class="form-group">
            @Html.Label("RequestDatetime", "Requested Date and Time:", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                <input type="text" name="RequestDatetime" id="RequestDatetime" value="@Model.RequestDatetime" class="form-control" required />
                @Html.ValidationMessage("RequestDatetime", "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, "Subject:", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                <input type="text" name="Subject" id="Subject" value="@Model.Subject" class="form-control" required />
                @Html.ValidationMessage("Subject", "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, "Message:", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                <textarea class="form-control" id="Message" name="Message" cols="12" rows="6" placeholder="enter your message here." required>@Model.Message</textarea>
                @Html.ValidationMessage("Message", "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <input type="submit" value="Update" class="btn btn-default" id="btn-update" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/Appointments/edit.js")
}

TiminsHospitalProjectV3/Views/Appointments/List.cshtml
@model IEnumerable<TiminsHospitalProjectV3.Models.Appointment>
@Styles.Render("~/Content/Appointments/List.css")


@{
    ViewBag.Title = "List";
    string searchStatus = (string)ViewData["searchStatus"];
    string[] statuses = { "Accepted", "Rejected", "Pending" };
}


<h2>List Of Appointment Requests </h2>
<hr />
<div class="row" id="filter-row">
    <div class="col-md-9">
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
    </div>
    <div class="col-md-3">
        @using (Html.BeginForm("List", "Appointments", FormMethod.Get))
        {
            <div class="form-group">
                @Html.Label("Sort by:", new { @class = "control-label" })
                <select name="searchStatus" id="searchStatus">
                    @for (int i = 0; i < statuses.Length; i++)
                    {
                        if (string.Equals(searchStatus, i.ToString()))
                        {
                            <option value="@i" selected>@statuses[i] </option>
                        }
                        else
                        {
                            <option value="@i">@statuses[i] </option>
                        }
                    }
                    @if (string.Equals(searchStatus, "all"))
                    {
                        <option value="all" selected>All </option>
                    }
                    else
                    {
                        <option value="all">All</option>
                    }
                </select>
                <input type="submit" value="Refine" class="" id="btn-refine"/>
            </div>
        }
    </div>
</div>

<div class="container">
    @if (Model.Count() > 0)
     {
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">
                        @Html.DisplayName("Patient")
                    </th>
                    <th scope="col">
                        @Html.DisplayName("Physician")
                    </th>

                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Subject)
                    </th>

                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th>
                        @Html.DisplayName("Sent On")
                    </th>
                    <th scope="col">
                        @Html.DisplayName("Decision Made On")
                    </th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.PatientUser.FirstName)
                            @Html.DisplayFor(modelItem => item.PatientUser.LastName)
                        </td>
                        <td>
                            Dr
                            @Html.DisplayFor(modelItem => item.PhysicianUser.FirstName)
                            @Html.DisplayFor(modelItem => item.PhysicianUser.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Subject)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Status)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SentOn)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DecisionMadeOn)
                        </td>
                        <td>
                            @if (item.Status == TiminsHospitalProjectV3.Models.AppointmentStatus.Pending)
                            {
                                @Html.ActionLink("Edit", "Edit", new { id = item.ID })
                                <span>|</span>

                            }
                            @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                            @Html.ActionLink("Delete", "DeleteConfirm", new { id = item.ID })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="page-paginate">
            @{
                int PageNum = Convert.ToInt32(ViewData["PageNum"]);
                int MaxPageNum = Convert.ToInt32(ViewData["MaxPageNum"]);
            }
            <ul>

                @if (PageNum > 1)
                {
                    int PrevPage = PageNum - 1;
                    <li>

                        @Html.ActionLink("Prev", "List", new { pageNum = PrevPage, searchStatus = searchStatus }, null)
                    </li>
                    <li>|</li>

                }
                <li>@ViewData["PageNum"] of @ViewData["MaxPageNum"]</li>

                @if (PageNum < MaxPageNum)
                {
                    <li>|</li>
                    int NextPage = PageNum + 1;
                    <li>
                        @Html.ActionLink("Next", "List", new { pageNum = NextPage, searchStatus = searchStatus }, null)
                    </li>
                }

            </ul>
        </div>
     }
     else {
<p>
    You don't have any appointement matching your search for now. You can create one @Html.ActionLink("here", "Create").
</p>
                }
</div>